### ISSUE TITLE
@ac2ca9b broke endwise compatibility

### ISSUE THREAD

**Issue by mogelbrod** [Townk/vim-autoclose#33] opened 2012-05-22 21:15 UTC
ac2ca9ba4de085b0c2849363affa81adc1a85f74 seems to have broken compatibility with [vim-endwise](https://github.com/tpope/vim-endwise). I'm not sure what caused it as I don't have much knowledge of writing vim plugins, but autoclose seems to prevent <CR> from triggering endwise in insert mode.

To reproduce:

```
$ vim
:set ft=ruby<CR>
i
def test<CR>
```

This should append `end` to a new line but does not right now.

**Comment by artm** [comment] 2012-06-05 10:22
hmm... I use both. I might have some special plugin-aware configuration snippet for ruby though... I'll get back to you on this.

**Comment by jfelchner** [comment] 2012-06-16 04:17
Same problem here.  Reverting to b63af10761e5b783aecd189847c73ca3202bb5fd made endwise work again.

**Comment by jwhitley** [comment] 2012-06-16 22:04
Same problem here.  I only recently added vim-autoclose to my config, and noticed that endwise had stopped working.

**Comment by jwhitley** [comment] 2012-06-20 22:37
FWIW, I made a local branch off of HEAD (515346b) that reverts the "Expand Enter" and "Expand Space" commits (16e1120 and 8ded63e, respectively).  That also appears to fix endwise compatibility.

**Comment by jfelchner** [comment] 2012-06-21 06:31
@artm any word on this?  Do you need any more information from us?

**Comment by ejholmes** [comment] 2012-07-01 06:01
Having the same issue, it would be nice to get this fixed without having to revert to an older version of vim-autoclose.

**Comment by Townk** [comment] 2012-07-15 19:23
I'm not a Ruby programmer but I'll get a Vanilla Vim with AutoClose and endwise to test this. This should be a meter of allowing the <Enter> key to be remapped but I'll check tonight.

**Comment by begriffs** [comment] 2012-09-08 17:21
Not sure how the following affects autoclose, but I noticed that this patch fixes endwise compatibility in ac2ca9b:

```
diff --git a/plugin/AutoClose.vim b/plugin/AutoClose.vim
index 3072e7a..475aa08 100644
--- a/plugin/AutoClose.vim
+++ b/plugin/AutoClose.vim
@@ -432,9 +432,6 @@ function! s:CreateExtraMaps()
     if b:AutoCloseExpandSpace
         inoremap <buffer> <silent> <Space>      <C-R>=<SID>Space()<CR>
     endif
-    if len(b:AutoCloseExpandEnterOn) > 0
-        inoremap <buffer> <silent> <CR>      <C-R>=<SID>Enter()<CR>
-    endif

     if g:AutoClosePreserveDotReg
         " Fix the re-do feature by flushing the char buffer on key movements (including Escape):
```

**Comment by artm** [comment] 2012-09-09 08:43
(I'm back from dead)

The same effect could also have been achieved by adding

```
let g:AutoCloseExpandEnterOn=""
```

to your ~/.vimrc

I don't seem to have anything special in my configuration to fix AutoClose / endwise incompatibility - but I'm sure they both work when I'm editing ruby. I'll try to reproduce this.

**Comment by artm** [comment] 2012-09-09 09:47
Please try current HEAD, it disables Enter expansion by default.

**Comment by jwhitley** [comment] 2012-09-10 21:59
Works for me: @artm, confirmed with current HEAD of vim-endwise and vim-autoclose.  Thanks!

**Comment by artm** [comment] 2012-09-11 05:01
great, closing then

**Closed as completed by artm** 2012-09-11 05:01 UTC
